routes/web.php
<?php

use App\Http\Controllers\Admin\Asnaf\SemakanPermohonanAsnafController;
use App\Http\Controllers\PermohonanAkaunController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * landing page routes
 */
Route::get('/', [App\Http\Controllers\Landing\LandingController::class, 'index'])->name('landing.index');


Auth::routes();

Route::prefix('asnaf')->group(function () {
    Route::resource('permohonan-akaun', PermohonanAkaunController::class);
});

Route::group([
    'middleware' => ['auth']
], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', ]
], function () {
    Route::resource('semakan-permohonan-asnaf', SemakanPermohonanAsnafController::class);
});

app/Models/PermohonanAsnaf.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Base\BaseModel;

class PermohonanAsnaf extends BaseModel
{
    // use \OwenIt\Auditing\Auditable;

    /**
     * enable soft delete
     *
     * @var timestamp
     */
    // use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'PermohonanAsnaf';

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'PermohonanAsnafId';

    /**
     * @var array
     */
    protected $fillable = [

		'Nama',
		'NoKp',
		'NoTel',
        'Email',
		'Jantina',
		'StatusPerkahwinan',
		'Alamat',
		'NegeriId',
		'DaerahId',
		'Poskod',
		'Kariah',
		'Status',
		'PegawaiSemak',
        'Catatan',
		'created_at',
		'updated_at',
    ];

    /**
     * reference to ..
     */
    protected $jantinaGroup = [
        1 => 'Lelaki',
        2 => 'Perempuan'
    ];

    protected $statusPerkahwinanGroup = [
        1 => 'Bujang',
        2 => 'Berkahwin'
    ];

    protected $statusPermohonanGroup = [
        1 => 'Baru',
    ];

    /**
     * append attributes
     */
    protected $appends = [
        'JantinaName',
        'StatusPerkahwinanName',
        'StatusPermohonanName'
    ];

    public function getNameAttribute($attribute, $group)
    {
        if (empty($this->attributes[$attribute])) {
            return '-';
        }

        return $group[$this->attributes[$attribute]];
    }

    public function getJantinaNameAttribute()
    {
        return $this->getNameAttribute('Jantina', $this->jantinaGroup);
    }

    public function getStatusPerkahwinanNameAttribute()
    {
        return $this->getNameAttribute('StatusPerkahwinan', $this->statusPerkahwinanGroup);
    }

    public function getStatusPermohonanNameAttribute()
    {
        switch ($this->attributes['Status']) {
            case 1:
                return '<span class="badge rounded-pill bg-primary">BARU</span>';
                break;
            case 10:
                return '<span class="badge rounded-pill bg-success">DITERIMA</span>';
                break;
            default:
                return '-';
                break;
        }
    }


    /**
     * relastionship table
     */
    public function negeri()
    {
        // Specify the foreign key and local key
        return $this->belongsTo(RefNegeri::class, 'NegeriId', 'RefNegeriId');
    }

    public function daerah()
    {
        return $this->belongsTo(RefDaerah::class, 'DaerahId', 'RefDaerahId');
    }

}

resources/views/modules/admin/permohonan-asnaf/semakan/edit.blade.php
@extends('layout.app')

@section('css')
@endsection

@section('content')
    <nav class='page-breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'>Permohonan Asnaf</li>
            <li class='breadcrumb-item active' aria-current='page'>Maklumat Pemohon</li>
        </ol>
    </nav>

    <div class='row'>
        <div class='col-lg-12'>
            @include('common.alert')

            <div class='card'>
                <div class='card-header'>
                    <h4 class='card-title'>Permohonan Asnaf</h4>
                    <p class='card-title-desc'>Maklumat Pemohon</p>
                </div>
                <div class='card-body'>
                    <div class="col-md-12">
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Nama Pemohon :</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->Nama) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">NoKp Pemohon:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ $permohonan->NoKp }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">E-mal:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ $permohonan->Email }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">No Tel:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->NoTel) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Jantina:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->jantinaName) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Status Perkahwinan:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->statusPerkahwinanName) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Alamat:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->Alamat) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Negeri:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->negeri->Negeri) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Daerah:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->daerah->Daerah) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Poskod:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->Poskod) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Kariah:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{{ strtoupper($permohonan->Kariah) }}</p>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-md-2">
                                <p class="text-dark font-weight-bold">Status Permohonan:</p>
                            </div>
                            <div class="col-md-10">
                                <p>{!! $permohonan->StatusPermohonanName !!}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </br>
            <div class="card">
                <form action="{{ route('semakan-permohonan-asnaf.update', $permohonan->PermohonanAsnafId) }}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="card-header">
                        <h4 class="card-title">Tindakan Pegawai</h4>
                    </div>
                    <div class="card-body">
                        <div class="col-md-12">
                            <div class="row mb-2">
                                <div class="col-md-2">
                                    <p class="text-dark font-weight-bold">Tindakan</p>
                                </div>
                                <div class="col-md-10">
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input" value="10" name="Tindakan" id="terima">
                                        <label class="form-check-label" for="terima">Terima</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input type="radio" class="form-check-input" value="20" name="Tindakan" id="tolak">
                                        <label class="form-check-label" for="tolak">Tolak</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row mb-2">
                                <div class="col-md-2">
                                    <p class="text-dark font-weight-bold">Catatan</p>
                                </div>
                                <div class="col-md-10">
                                    <textarea id="maxlength-textarea" class="form-control" maxlength="1000" rows="3" name="Catatan" placeholder="Ulasan penyiasat."></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent">
                        <div class="form-group row">
                            <div class="col">
                                <a href="{{ route('semakan-permohonan-asnaf.index') }}" type="button" class="btn btn-danger btn-xs"">KEMBALI KE SENARAI</a>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-success btn-xs">HANTAR</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script>
    $(document).ready(function() {

    });
</script>
@endsection

resources/views/modules/admin/permohonan-asnaf/semakan/index.blade.php
@extends('layout.app')

@section('css')
@endsection

@section('content')
    <nav class='page-breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'>Permohonan Asnaf</li>
            <li class='breadcrumb-item active' aria-current='page'>Belum Disemak</li>
        </ol>
    </nav>

    <div class='row'>
        <div class='col-lg-12'>
            @include('common.alert')

            <div class='card'>
                <div class='card-header'>
                    <h4 class='card-title'>Permohonan Asnaf</h4>
                    <p class='card-title-desc'>Senarai Permohonan Baru</p>
                </div>
                <div class='card-body'>
                    <div class='col-sm-12 table-responsive'>
                        <table class='table dataTable no-footer' id='kt_datatable'
                            data-route='{{ route('semakan-permohonan-asnaf.index') }}'></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script>
    $(document).ready(function() {
        var table = $('#kt_datatable')

        var SemakanDT = table.DataTable({
            responsive: true,
            searchDelay: 500,
            processing: true,
            serverSide: true,
            scrollCollapse: true,
            pagingType: 'full_numbers',
            ordering: false,
            responsive: true,
            language: {
                search: "Carian :"
            },
            ajax: {
                url: table.data('route'),
                method: 'GET',
                dataType: 'json',
                dataSrc: "data",
            },
            columns: [{
                    title: '#',
                    data: 'PermohonanAsnafId',
                    render: function(data, type, full, meta) {
                        return meta.row + 1;
                    }
                },
                {
                    title: 'Name',
                    data: 'Nama'
                },
                {
                    title: 'NoKp',
                    data: 'NoKp'
                },
                {
                    title: 'Jantina',
                    data: 'JantinaName',
                },
                {
                    title: 'Status Perkahwinan',
                    data: 'StatusPerkahwinanName',
                },
                {
                    title: 'No Tel',
                    data: 'NoTel',
                },
                {
                    title: 'Status',
                    data: 'StatusPermohonanName',
                },
                {
                    title: 'Tarikh Daftar',
                    data: 'created_at',
                    render: function(row) {
                        if (row == null) {
                            return '-';
                        } else {
                            return moment(row).format('DD/MM/YYYY');
                        }
                    },
                },
                {
                    data: 'PermohonanAsnafId',
                    title: 'Tindakan',
                    orderable: false,
                    render: function(data, type, full, meta) {
                        return `\
                            <a href="javascript:;" id="${full.PermohonanAsnafId}" class="edit">\
                                <svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-edit'><path d='M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7'></path><path d='M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z'></path></svg>\
                            </a>\
                            <a href="javascript:;" id="${full.PermohonanAsnafId}" class="delete" style="color:red">\
                                <svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-trash-2'><polyline points='3 6 5 6 21 6'></polyline><path d='M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2'></path><line x1='10' y1='11' x2='10' y2='17'></line><line x1='14' y1='11' x2='14' y2='17'></line></svg>\
                            </a>\
                        `;
                    },
                },
            ],
        });

        table.each(function() {
            var datatable = $(this);
            // SEARCH - Add the placeholder for Search and Turn this into in-line form control
            var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
            search_input.attr('placeholder', 'Search');
            search_input.removeClass('form-control-sm');
            // LENGTH - Inline-Form control
            var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
            length_sel.removeClass('form-control-sm');
        });

        // EDIT
        $('body').on('click', '.edit', function() {
            var PermohonanAsnafId = $(this).attr('id');
            var route = table.data('route') + '/' + PermohonanAsnafId + '/edit';

            window.location.href = route;
        });

        // DELETE
        $('body').on('click', '.delete', function() {
            var PermohonanAsnafId = $(this).attr('id');
            var url = table.data('route') + '/' + PermohonanAsnafId;

            Swal.fire({
                title: 'NOTIFIKASI',
                text: 'Adakah anda pasti?',
                icon: 'info',
                showCancelButton: true,
                confirmButtonColor: '#038cfc',
                cancelButtonColor: '#999',
                confirmButtonText: 'YA',
                cancelButtonText: 'BATAL',
                allowOutsideClick: false
            }).then((response) => {
                if (response.value) {
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function(data) {
                            statusCode = 2;
                            window.helper.success(data, statusCode)
                            SemakanDT.draw();
                        },
                        error: function(data) {
                            $('#alert').removeClass('alert-success').addClass('alert-danger');
                            $('#icon').removeClass('flaticon2-check-mark').addClass('flaticon2-delete');
                            $("#text").html(data.message);
                            $(".alert").delay(3000).fadeOut();
                            SemakanDT.draw();
                        }
                    });
                }
            });
        });

    });
</script>
@endsection